language: php
php:
- 5.6
- 7.0

install:
  - composer install
  - composer require codacy/coverage

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/codacycoverage clover
